// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0RJ5F4OyilvN_X0MwS_U2r22MYCKmm0Y',
    appId: '1:753949466240:web:aa14e3cbf5bd8d76515065',
    messagingSenderId: '753949466240',
    projectId: 'social-app-4b049',
    authDomain: 'social-app-4b049.firebaseapp.com',
    storageBucket: 'social-app-4b049.firebasestorage.app',
    measurementId: 'G-2KLC2PLG6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC1zHmJ0fIMG8TSA3Q9b1s8HNxkqYvROU',
    appId: '1:753949466240:android:0a33f4065cb55fd6515065',
    messagingSenderId: '753949466240',
    projectId: 'social-app-4b049',
    storageBucket: 'social-app-4b049.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOuguIN6zUd_Lt6JdruhHzar7VF8JIsDI',
    appId: '1:753949466240:ios:5f590a412b90fe6f515065',
    messagingSenderId: '753949466240',
    projectId: 'social-app-4b049',
    storageBucket: 'social-app-4b049.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOuguIN6zUd_Lt6JdruhHzar7VF8JIsDI',
    appId: '1:753949466240:ios:5f590a412b90fe6f515065',
    messagingSenderId: '753949466240',
    projectId: 'social-app-4b049',
    storageBucket: 'social-app-4b049.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0RJ5F4OyilvN_X0MwS_U2r22MYCKmm0Y',
    appId: '1:753949466240:web:30af60450cd296d4515065',
    messagingSenderId: '753949466240',
    projectId: 'social-app-4b049',
    authDomain: 'social-app-4b049.firebaseapp.com',
    storageBucket: 'social-app-4b049.firebasestorage.app',
    measurementId: 'G-CHT7F40HDE',
  );
}
